
kind: Service
apiVersion: v1
metadata:
  name: image
spec:
  selector:
    app: image
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-deployment
  labels:
    app: image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image
  template:
    metadata:
      labels:
        app: image
    spec:
      initContainers:
      - name: init-image-db
        image: busybox
        command: ['sh', '-c', "until nslookup image-db-mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

      - name: migrate
        image: migrate/migrate
        args: ["-source", "github://ezio1119:4a0baad88cbd2037e554d85bd63b4449d306a6cf@ezio1119/fishapp-image/db/sql", "-database", "mysql://root:password@tcp(image-db-mysql:3306)/image_DB", "up"]

      containers:
      - name: image
        image: image
        ports:
        - containerPort: 50051
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 1
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr=:50051"]
          initialDelaySeconds: 1
        env:
        - name: DB_HOST
          value: image-db-mysql