
kind: Service
apiVersion: v1
metadata:
  name: post
spec:
  selector:
    app: post
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: post-deployment
  labels:
    app: post
spec:
  replicas: 1
  selector:
    matchLabels:
      app: post
  template:
    metadata:
      labels:
        app: post
    spec:
      initContainers:
      # - name: init-post-db
      #   image: busybox
      #   command: ['sh', '-c', "until nslookup post-db-mysql.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

      - name: migrate
        image: migrate/migrate
        args: ["-source", "github://ezio1119:78591659505da5f3a09c15c21162920402703f1b@ezio1119/fishapp-post/db/sql", "-database", "mysql://root:password@tcp(post-db-mysql:3306)/post_DB", "up"]

      # - name: init-nats-streaming
      #   image: busybox
      #   command: ['sh', '-c', "until nslookup nats-streaming.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

      # - name: init-image
      #   image: busybox
      #   command: ['sh', '-c', "until nslookup image.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]

      containers:
      - name: post
        image: post
        ports:
        - containerPort: 50051
        # readinessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        #   initialDelaySeconds: 1
        # livenessProbe:
        #   exec:
        #     command: ["/bin/grpc_health_probe", "-addr=:50051"]
        #   initialDelaySeconds: 1
        env:
        - name: DB_HOST
          value: post-db-mysql
        - name: TZ
          value: Asia/Tokyo