configurationFiles:
  my.cnf: |-
    [mysqld]
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    log_bin=chatdb.bin
    binlog_format=ROW
    server-id=1
mysqlDatabase: chat_DB
timezone: Asia/Tokyo
mysqlRootPassword: password