kind: Service
apiVersion: v1
metadata:
  name: nats-streaming
spec:
  selector:
    app: nats-streaming
  ports:
  - protocol: TCP
    port: 4223
    targetPort: 4223
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-deployment
  labels:
    app: nats-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats-streaming
  template:
    metadata:
      labels:
        app: nats-streaming
    spec:
      containers:
      - name: nats-streaming
        image: nats-streaming:alpine
        ports:
        - containerPort: 4223
        args: ["-p", "4223", "-m", "8223", "-cid", "fishapp-cluster"]